#ifndef CODES_H
#define CODES_H
enum ERROR_CODES { NO_ERRORS, INDEX_OUT_OF_RANGE };

enum PRINT_CODES { INFO, WARNING, ERROR };

enum TASK_STATUS { UNCHECKED, CHECKED, ARCHIVED_UNCHECKED, ARCHIVED_CHECKED };

enum EXIT_CODES {
  ACTION_NOT_PERFORMED,
  ACTION_PERFORMED,

  TASK_ADDED_SUCCESSFULLY,
  TASK_NOT_ADDED,
  TASK_REMOVED_SUCCESSFULLY,
  TASK_NOT_REMOVED,
  TASK_CHECKED_SUCCESSFULLY,
  TASK_NOT_CHECKED,
  TASK_UNCHECKED_SUCCESSFULLY,
  TASK_NOT_UNCHECKED,
};
#endif
